version: "3.5"

services:
    api01: &api
        image: rinha
        hostname: api01
        environment:
            - DB_HOSTNAME=db
        ports:
            - "3333:3333"
        depends_on:
            - db

    api02:
        <<: *api
        hostname: api02
        environment:
            - DB_HOSTNAME=db
        ports:
            - "3334:3333"

    db:
        image: postgres:latest
        hostname: db
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_DB=rinhabackend
        ports:
            - "5432:5432"
        volumes:
            - ./db/script.sql:/docker-entrypoint-initdb.d/script.sql
networks:
    default:
        driver: bridge
        name: rinha-nginx-2024q1

