version: "3.5"

services:
    api01: &api
        image: rinha
        hostname: api01
        environment:
            - DB_HOSTNAME=db
            - DB_PORT=5432
            - SQL_INIT=never
            - DDL_AUTO=none
        ports:
            - "3333:3333"
        depends_on:
            - db

    api02:
        <<: *api
        hostname: api02
        environment:
            - DB_HOSTNAME=db
            - DB_PORT=5432
            - SQL_INIT=never
            - DDL_AUTO=none
        ports:
            - "3334:3333"

    nginx:
        image: nginx:latest
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - api01
            - api02
        ports:
            - "9999:9999"

    db:
        image: postgres:latest
        hostname: db
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_DB=rinhabackend
        ports:
            - "5432:5432"
        volumes:
            - ./script.sql:/docker-entrypoint-initdb.d/script.sql
networks:
    default:
        driver: bridge
        name: rinha-nginx-2024q1
