server:
    port: 3333
spring:
    sql:
        init:
            mode: ${SQL_INIT:always}
    jpa:
        defer-datasource-initialization: true
        database: POSTGRESQL
        show-sql: false
        hibernate:
            ddl-auto: ${DDL_AUTO:create-drop}
    datasource:
        platform: postgres
        url: jdbc:postgresql://${DB_HOSTNAME:localhost}:${DB_PORT:5432}/${DB_NAME:rinhabackend}
        username: postgres
        password: postgres
        driverClassName: org.postgresql.Driver
        initialization-mode: always

