server:
    port: 3333
spring:
    sql:
        init:
            mode: always
    jpa:
        defer-datasource-initialization: true
        database: POSTGRESQL
        show-sql: false
        hibernate:
            ddl-auto: create-drop
    datasource:
        platform: postgres
        url: jdbc:postgresql://localhost:5432/rinhabackend
        username: postgres
        password: postgres
        driverClassName: org.postgresql.Driver
        initialization-mode: always
